In [0]:
import numpy as np

In [0]:
#1.- Crea un vector con valores dentro del rango 3 a el número que representa tu edad.
vector = np.array(range(3,38))
vector

Out[5]: array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37])

In [0]:
#2.- Crea un arreglo con los siguientes elementos: [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
arreglo = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
arreglo

Out[16]: array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [0]:
#3.- Ordena de forma ascendiente dicho arreglo.
arreglo.sort()
arreglo

Out[19]: array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])